// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ApiForm: typeof import('./components/form/ApiForm.vue')['default']
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Checkbox: typeof import('./components/form/Checkbox.vue')['default']
    EmojioneMoneyWithWings: typeof import('~icons/emojione/money-with-wings')['default']
    ErrorSummary: typeof import('./components/form/ErrorSummary.vue')['default']
    FormLoading: typeof import('./components/form/FormLoading.vue')['default']
    InputDescription: typeof import('./components/form/InputDescription.vue')['default']
    LogosDigitalOcean: typeof import('~icons/logos/digital-ocean')['default']
    LogosJamstackIcon: typeof import('~icons/logos/jamstack-icon')['default']
    LogosNextjsIcon: typeof import('~icons/logos/nextjs-icon')['default']
    LogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    LogosVisualStudio: typeof import('~icons/logos/visual-studio')['default']
    LogosVisualStudioCode: typeof import('~icons/logos/visual-studio-code')['default']
    LogosVue: typeof import('~icons/logos/vue')['default']
    MarkdownPage: typeof import('./components/MarkdownPage.vue')['default']
    MdiArrowLeftThin: typeof import('~icons/mdi/arrow-left-thin')['default']
    MdiCheckboxBlankCircleOutline: typeof import('~icons/mdi/checkbox-blank-circle-outline')['default']
    MdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    NotoPineapple: typeof import('~icons/noto/pineapple')['default']
    PrimaryButton: typeof import('./components/form/PrimaryButton.vue')['default']
    README: typeof import('./components/README.md')['default']
    SecondaryButton: typeof import('./components/form/SecondaryButton.vue')['default']
    ShellCommand: typeof import('./components/ShellCommand.vue')['default']
    SimpleIconsBlazor: typeof import('~icons/simple-icons/blazor')['default']
    TextInput: typeof import('./components/form/TextInput.vue')['default']
  }
}

export { }
